# Generated by Django 3.2.6 on 2022-01-08 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_head',
            },
        ),
        migrations.CreateModel(
            name='AccountSubHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subhead', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('income', 'INCOME'), ('expense', 'EXPENSE')], default='income', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.accounthead')),
            ],
            options={
                'db_table': 'account_subhead',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='', max_length=200)),
                ('opening_balance', models.FloatField()),
                ('total_balance', models.FloatField(default=0)),
                ('account_type', models.CharField(blank=True, choices=[('pettycash', 'PETTYCASH'), ('bank', 'BANK')], max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_account',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'cash'), (2, 'online'), (3, 'cheque'), (4, 'upi'), (5, 'razorpay'), (6, 'paytm'), (7, 'gpay'), (8, 'phonepe'), (9, 'bhim')], primary_key=True, serialize=False)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'cash'), ('ONLINE', 'online'), ('CHEQUE', 'cheque'), ('UPI', 'upi'), ('RAZORPAY', 'razorpay'), ('PAYTM', 'paytm'), ('GPAY', 'gpay'), ('PHONEPE', 'phonepe'), ('BHIM', 'bhim')], max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, default=0)),
                ('count', models.CharField(blank=True, max_length=100, null=True)),
                ('till_date', models.DateField(blank=True, null=True)),
                ('is_percentage', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promocode',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='file/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('account_sub_head', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.accountsubhead')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.bankaccount')),
                ('payment_method', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.paymentmethod')),
            ],
            options={
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('file', models.FileField(blank=True, null=True, upload_to='file/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('account_sub_head', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.accountsubhead')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.bankaccount')),
                ('payment_method', models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.paymentmethod')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
