# Generated by Django 3.2.7 on 2021-09-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0002_auto_20210907_1939_0003_auto_20210907_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lab_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lab_name',
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'is_superadmin'), (2, 'is_admin'), (3, 'is_student'), (4, 'is_teacher')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, choices=[('IS_SUPERADMIN', 'is_superadmin'), ('IS_ADMIN', 'is_admin'), ('IS_STUDENT', 'is_student'), ('IS_TEACHER', 'is_teacher')], max_length=100, null=True),
        ),
    ]
