# Generated by Django 3.2.6 on 2022-01-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.institute')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.session')),
            ],
            options={
                'db_table': 'fee_type',
            },
        ),
        migrations.CreateModel(
            name='FeeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.institute')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.session')),
            ],
            options={
                'db_table': 'fee_term',
            },
        ),
        migrations.CreateModel(
            name='FeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.department')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.institute')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.session')),
                ('term_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.feeterm')),
            ],
            options={
                'db_table': 'feeGroup',
            },
        ),
    ]
