# Generated by Django 3.2.6 on 2022-01-08 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('student_status', models.CharField(blank=True, choices=[('current', 'CURRENT'), ('dropout', 'DROPOUT'), ('passout', 'PASSOUT')], default='current', max_length=50)),
                ('student_religion', models.CharField(blank=True, choices=[('hindu', 'HINDU'), ('muslim', 'MUSLIM'), ('sikh', 'SIKH'), ('ishi', 'ISHI')], max_length=50, null=True)),
                ('student_category', models.CharField(blank=True, choices=[('general', 'GENERAL'), ('ebc', 'EBC'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST')], max_length=50, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.department')),
                ('session_admit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='college_data.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='SemesterWiseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('semester_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_data.semestersession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'semester_wise_student',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_certificate_name', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('authority_name', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachment/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
    ]
